# Find Difference in a String
# You are given two strings s and t.
# String t is generated by random shuffling string s and 
# then add one more letter at a random position.
# Return the letter that was added to t.
# Example 1:
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:
# Input: s = "", t = "y"
# Output: "y"
# Example 3:
# Input: s = "a", t = "aa"
# Output: "a"
# Example 4:
# Input: s = "ae", t = "aea"
# Output: "a"

def find_diff(s,t):
    t_list = list(t)
    result=""
    for letter in s:
        t_list.remove(letter)
    for char in t_list:
        result += char
    return result

        
print(find_diff("txt", "atxqWxXtexxx"))

# better in time complexity - try hashmap


def find_diff(s,t):
    s_map = {}
    t_map = {}
    
    for char in s:
        if char not in s_map:
            s_map[char] = 1
        elif char in s_map:
            s_map[char] +=1 
        
